interface Post {
  id: number;
  tags: string;
  file_type: string;
  score: number;
  downloaded: boolean;
  preview_url: string;
  file_url: string;
  sample_url: string;
  file_path: string;
  width: number;
  height: number;
  file_size: number;
  source: string;
  downloadedAt: string;
  _index: number;
}

interface Profile {
  liked_posts: number[];
  hidden_posts: number[];
  presets: any[];
  fav_tags: string[];
  hidden_tags: string[];
  nickname: string;
  avatar: string;
}

interface AppState {
  posts: Post[];
  page: number;
  loading: boolean;
  hasMore: boolean;
  query: string;
  isLocal: boolean;
  viewerOpen: boolean;
  viewerIndex: number;
  recommendActive: boolean;
  settingsOpen: boolean;
  profileOpen: boolean;
  downloadQueue: Set<number>;
  downloading: Set<number>;
  focusedIndex: number;
  profile: Profile;
  selected: Set<number>;
  slideshowActive: boolean;
  slideshowSpeed: number;
  minId: number | null;
  hoveredIndex: number;
  sortBy: string;
  displayMode: string;
  displayIds: number[];
  theme: string;
  gridCols: number | null;
  autoRefreshFeed: boolean;
  activeProvider: string;
  ratingFilter: string;
  viewedFilter: string;
  accent: string;
  autoDownload: boolean;
  relatedChain: boolean;
  user: { username: string; nickname: string; avatar: string } | null;
}

interface AppElements {
  grid: HTMLElement;
  sentinel: HTMLElement;
  searchInput: HTMLInputElement;
  suggestions: HTMLElement;
  searchBox: HTMLElement | null;
  viewer: HTMLElement;
  viewerHead: HTMLElement;
  viewerFoot: HTMLElement;
  viewerContent: HTMLElement;
  viewerInfo: HTMLElement;
  viewerTags: HTMLElement;
  viewerProgress: HTMLElement;
  relations: HTMLElement;
  viewerComments: HTMLElement;
  viewerDownload: HTMLElement;
  viewerFullscreen: HTMLElement;
  viewerMobileActions: HTMLElement;
  viewerMobileToggle: HTMLElement;
  zoomIn: HTMLElement;
  zoomOut: HTMLElement;
  zoomFit: HTMLElement;
  zoomLabel: HTMLElement;
  zoomHud: HTMLElement;
  zThumbX: HTMLElement;
  zThumbY: HTMLElement;
  viewerClose: HTMLElement;
  viewerLike: HTMLElement;
  viewerHide: HTMLElement;
  viewerLikeM: HTMLElement;
  viewerHideM: HTMLElement;
  viewerFullscreenM: HTMLElement;
  prevBtn: HTMLElement;
  nextBtn: HTMLElement;
  settingsPanel: HTMLElement;
  settingsClose: HTMLElement;
  btnLocal: HTMLElement;
  statsModal: HTMLElement;
  statsBody: HTMLElement;
  statsClose: HTMLElement;
  toast: HTMLElement;
  statusText: HTMLElement;
  btnSaveSettings: HTMLElement;
  apiKeysList: HTMLElement;
  btnAddApiKey: HTMLElement;
  settingProxy: HTMLInputElement;
  settingSavepath: HTMLInputElement;
  settingProvider: HTMLSelectElement;
  settingConcurrent: HTMLInputElement;
  settingTheme: HTMLSelectElement;
  settingGrid: HTMLSelectElement;
  settingAccent: HTMLElement;
  settingLang: HTMLSelectElement;
  settingAutoRefresh: HTMLInputElement;
  profilePanel: HTMLElement;
  profileClose: HTMLElement;
  presetName: HTMLInputElement;
  btnSavePreset: HTMLElement;
  presetCurrent: HTMLElement;
  presetsList: HTMLElement;
  likesList: HTMLElement;
  hidesList: HTMLElement;
  favTagsList: HTMLElement;
  hiddenTagsList: HTMLElement;
  favPresetSelect: HTMLSelectElement;
  hiddenPresetSelect: HTMLSelectElement;
  favTagInput: HTMLInputElement;
  hiddenTagInput: HTMLInputElement;
  btnAddFavTag: HTMLElement;
  btnAddHiddenTag: HTMLElement;
  likesEmpty: HTMLElement;
  hidesEmpty: HTMLElement;
  batchBar: HTMLElement;
  batchCount: HTMLElement;
  batchDownload: HTMLElement;
  batchHide: HTMLElement;
  batchClear: HTMLElement;
  batchLike: HTMLElement;
  batchCollect: HTMLElement;
  historyDropdown: HTMLElement;
  slideshowBtn: HTMLElement;
  btnHome: HTMLElement;
  viewerLoader: HTMLElement;
  profileSuggestions: HTMLElement;
  favSuggestions: HTMLElement;
  ssSpeedInput: HTMLInputElement;
  modeBar: HTMLElement;
  modeBarText: HTMLElement;
  modeBarRefresh: HTMLElement;
  modeBarClose: HTMLElement;
  btnLikesGrid: HTMLElement;
  btnHidesGrid: HTMLElement;
  btnLikesMore: HTMLElement;
  btnHidesMore: HTMLElement;
  tagFilter: HTMLInputElement;
  tagFilterCount: HTMLElement;
  btnClearFavTags: HTMLElement;
  btnClearHiddenTags: HTMLElement;
  profileAvatar: HTMLElement;
  profileAvatarImg: HTMLImageElement;
  profileAvatarFile: HTMLInputElement;
  profileNickname: HTMLInputElement;
  btnDBClean: HTMLElement;
  inputCurrentPassword: HTMLInputElement;
  inputNewPassword: HTMLInputElement;
  btnChangePassword: HTMLElement;
  btnLogoutOthers: HTMLElement;
  dlProgress: HTMLElement;
  dlProgressBar: HTMLElement;
  dlProgressText: HTMLElement;
  dlPause: HTMLElement;
  dlResume: HTMLElement;
  queueModal: HTMLElement;
  queueBody: HTMLElement;
  queueClose: HTMLElement;
  btnExportPresets: HTMLElement;
  btnImportPresets: HTMLElement;
  presetImportFile: HTMLInputElement;
  btnHeaderMenu: HTMLElement;
  headerMenu: HTMLElement;
  searchClear: HTMLElement;
  providerBadge: HTMLElement;
  providerMenu: HTMLElement;
  providerMenuList: HTMLElement;
  ratingToggle: HTMLElement;
  feedProgress: HTMLElement;
  queryMeta: HTMLElement;
  viewedToggle: HTMLElement;
  btnAddAlias: HTMLElement;
  searchChips: HTMLElement;
  scrollProgress: HTMLElement;
  viewerRelated: HTMLElement;
  btnLikesDownload: HTMLElement;
  panelBackdrop: HTMLElement;
  confirmModal: HTMLElement;
  confirmTitle: HTMLElement;
  confirmMessage: HTMLElement;
  confirmOk: HTMLElement;
  confirmCancel: HTMLElement;
  confirmClose: HTMLElement;
  confirmBackdrop: HTMLElement;
  helpModal: HTMLElement;
  helpBody: HTMLElement;
  helpClose: HTMLElement;
  helpBackdrop: HTMLElement;
  btnFindDups: HTMLElement;
  btnCleanDups: HTMLElement;
  btnMergeDups: HTMLElement;
  dupsInfo: HTMLElement;
  viewerCollect: HTMLElement;
  collectMenu: HTMLElement;
  collectionName: HTMLInputElement;
  btnCreateCollection: HTMLElement;
  collectionsList: HTMLElement;
  tbCollections: HTMLElement;
  batchZip: HTMLElement;
  btnExportProfile: HTMLElement;
  btnImportProfile: HTMLElement;
  profileImportFile: HTMLInputElement;
  btnQRLogin: HTMLElement;
  btnRemotePush: HTMLElement;
  viewerSimilar: HTMLElement;
  [key: string]: HTMLElement | HTMLInputElement | HTMLSelectElement | HTMLImageElement | HTMLElement | null;
}

interface AppType {
  state: AppState;
  els: AppElements;
  [key: string]: any;
}

declare const App: AppType;

declare class BarcodeDetector {
  constructor(options?: { formats?: string[] });
  detect(source: Element | ImageBitmap | ImageData): Promise<Array<{ rawValue: string }>>;
}
